#!/usr/bin/env node
// Generates shared/src/abis/generated.ts from Foundry artifacts (run `forge build` first).
// Every ABI is emitted `as const`, so viem/wagmi infer argument and return types at compile time:
// a contract change that breaks the off-chain code fails `tsc`, not production.
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "out");

/** [exported name, artifact file, contract name] */
const CONTRACTS = [
  ["lendingPoolAbi", "LendingPool.sol", "LendingPool"],
  ["poolConfiguratorAbi", "PoolConfigurator.sol", "PoolConfigurator"],
  ["oracleManagerAbi", "OracleManager.sol", "OracleManager"],
  ["poolLensAbi", "PoolLens.sol", "PoolLens"],
  ["lendingVaultAbi", "LendingVault.sol", "LendingVault"],
  ["aclManagerAbi", "ACLManager.sol", "ACLManager"],
  ["interestRateModelAbi", "KinkedInterestRateModel.sol", "KinkedInterestRateModel"],
  ["mockErc20Abi", "MockERC20.sol", "MockERC20"],
  ["mockAggregatorAbi", "MockAggregator.sol", "MockAggregator"],
  ["timelockAbi", "TimelockController.sol", "TimelockController"],
];

function loadAbi(file, name) {
  const path = join(out, file, `${name}.json`);
  if (!existsSync(path)) throw new Error(`missing artifact ${path}: run forge build`);
  return JSON.parse(readFileSync(path, "utf8")).abi;
}

// Custom errors can be raised by linked libraries (LiquidationLogic) whose errors are not part of the
// pool's own ABI. Collect every error the protocol defines so revert reasons always decode.
function collectErrors() {
  const seen = new Map();
  for (const file of ["Errors.sol", "LiquidationLogic.sol", "LendingPool.sol", "OracleManager.sol", "PoolConfigurator.sol", "MockERC20.sol"]) {
    const dir = join(out, file);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) {
      for (const item of JSON.parse(readFileSync(join(dir, f), "utf8")).abi ?? []) {
        if (item.type === "error") seen.set(`${item.name}(${item.inputs.map((i) => i.type).join(",")})`, item);
      }
    }
  }
  // OpenZeppelin errors the protocol can surface (reentrancy lock, SafeERC20, SafeCast, ERC-4626).
  for (const [file, name] of [
    ["ReentrancyGuardTransient.sol", "ReentrancyGuardTransient"],
    ["SafeERC20.sol", "SafeERC20"],
    ["SafeCast.sol", "SafeCast"],
    ["ERC4626.sol", "ERC4626"],
  ]) {
    const path = join(out, file, `${name}.json`);
    if (!existsSync(path)) continue;
    for (const item of JSON.parse(readFileSync(path, "utf8")).abi) {
      if (item.type === "error") seen.set(`${item.name}(${item.inputs.map((i) => i.type).join(",")})`, item);
    }
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

let ts = `// AUTO-GENERATED by scripts/export-abis.mjs from Foundry artifacts. Do not edit by hand.\n\n`;
for (const [exportName, file, name] of CONTRACTS) {
  ts += `export const ${exportName} = ${JSON.stringify(loadAbi(file, name))} as const;\n\n`;
}
ts += `/** Every custom error the protocol (and its libraries) can revert with. */\n`;
ts += `export const protocolErrorsAbi = ${JSON.stringify(collectErrors())} as const;\n`;

const target = join(root, "shared", "src", "abis", "generated.ts");
writeFileSync(target, ts);
console.log(`wrote ${target} (${CONTRACTS.length} contracts, ${collectErrors().length} errors)`);
